import { useParams, Navigate } from 'react-router-dom';
import { Printer } from 'lucide-react';
import PackageArt from '../../components/illustrations/PackageArt';
import { StatusBadge } from '../../components/ui/Basics';
import { getInspection, isCompliant, RULE_ORDER, RULE_META, currentUser } from '../../data/mockData';

export default function Report() {
  const { id } = useParams();
  const inspection = getInspection(id);
  if (!inspection) return <Navigate to="/dashboard" replace />;

  const { declarations, product, category, rules, summary, date, inspector, measurement } = inspection;
  const compliant = isCompliant(summary);

  return (
    <div className="page report-page">
      <div className="page__head no-print">
        <h1>Report Preview</h1>
        <button type="button" className="btn btn--primary btn--md" onClick={() => window.print()}>
          <Printer size={15} aria-hidden="true" /> Print / Save as PDF
        </button>
      </div>

      <div className="report-doc">
        <header className="report-doc__head">
          <div>
            <div className="report-doc__brand">L.A.C.E.</div>
            <div className="report-doc__brand-sub">Legal Automated Compliance Engine</div>
          </div>
          <div className="report-doc__meta">
            <div>
              <span className="mono-label">Report ID</span>
              <strong>{inspection.id}</strong>
            </div>
            <div>
              <span className="mono-label">Date</span>
              <strong>{date}</strong>
            </div>
            <div>
              <span className="mono-label">Verdict</span>
              <StatusBadge status={inspection.status} />
            </div>
          </div>
        </header>

        <section className="report-doc__section report-doc__product">
          <div className="report-doc__art">
            <PackageArt declarations={declarations} />
          </div>
          <div>
            <span className="mono-label">Inspected Product</span>
            <h2>{product.name}</h2>
            <p>
              {product.brand} · {category}
            </p>
            <span className="mono-label">Inspector</span>
            <p>
              {inspector} — {currentUser.org}
            </p>
          </div>
        </section>

        <section className="report-doc__section">
          <span className="mono-label">Rule-by-Rule Results</span>
          <table className="data-table report-doc__table">
            <thead>
              <tr>
                <th>Rule</th>
                <th>Status</th>
                <th>Extracted Value</th>
                <th>Note</th>
              </tr>
            </thead>
            <tbody>
              {RULE_ORDER.map((ruleId) => {
                const rule = rules[ruleId];
                if (!rule) return null;
                return (
                  <tr key={ruleId}>
                    <td>{RULE_META[ruleId].label}</td>
                    <td>
                      <StatusBadge status={rule.status} size="sm" />
                    </td>
                    <td>{rule.extracted}</td>
                    <td>{rule.note || '—'}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>

        <section className="report-doc__section report-doc__measurement">
          <span className="mono-label">Measurement</span>
          <div className="report-doc__measurement-grid">
            <div>
              <span className="mono-label">Reference Length</span>
              <strong>{measurement.referenceMm.toFixed(1)} mm</strong>
            </div>
            <div>
              <span className="mono-label">Scale</span>
              <strong>{measurement.scaleMmPerPx.toFixed(3)} mm/px</strong>
            </div>
            <div>
              <span className="mono-label">Detected Text Height</span>
              <strong>{measurement.physicalTextMm.toFixed(2)} mm</strong>
            </div>
          </div>
        </section>

        <section className="report-doc__section report-doc__verdict">
          <span className="mono-label">Final Verdict</span>
          <h2 className={compliant ? 'is-pass' : 'is-fail'}>{compliant ? 'COMPLIANT' : 'NON-COMPLIANT'}</h2>
          <p>
            {summary.passed} Passed · {summary.warnings} Warnings · {summary.failed} Failed
          </p>
        </section>

        <footer className="report-doc__footer">
          Generated by L.A.C.E. — this report is a frontend mock for demonstration and contains no legal
          determination.
        </footer>
      </div>
    </div>
  );
}
